# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-05-27 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETL', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dim_product',
            name='prod_abbr',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='dim_product',
            name='product_id',
            field=models.IntegerField(),
        ),
    ]
