# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-05-27 22:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ETL', '0002_auto_20190528_0438'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dim_product',
        ),
    ]
