# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-05-27 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ETL', '0006_delete_dim_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='dim_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('prod_abbr', models.CharField(max_length=10)),
            ],
        ),
    ]
