# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-05-28 14:28
from __future__ import unicode_literals

import ETL.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETL', '0008_auto_20190528_0505'),
    ]

    operations = [
        migrations.CreateModel(
            name='input_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to=ETL.models.user_directory_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
