# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-05-29 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETL', '0010_auto_20190528_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='dim_primary_agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_agency_id', models.IntegerField()),
            ],
        ),
    ]
