# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-05-29 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETL', '0011_dim_primary_agency'),
    ]

    operations = [
        migrations.CreateModel(
            name='dim_agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_id', models.IntegerField()),
                ('appointment_year', models.IntegerField()),
                ('active_producers', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('min_age', models.IntegerField()),
                ('vendor_ind', models.CharField(max_length=10)),
                ('pl_start_year', models.IntegerField()),
                ('pl_end_year', models.IntegerField()),
                ('commisions_start_year', models.IntegerField()),
                ('commisions_end_year', models.IntegerField()),
                ('cl_start_year', models.IntegerField()),
                ('cl_end_year', models.IntegerField()),
                ('activity_notes_start_year', models.IntegerField()),
                ('activity_notes_end_year', models.IntegerField()),
            ],
        ),
    ]
