# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-05-29 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETL', '0012_dim_agency'),
    ]

    operations = [
        migrations.CreateModel(
            name='dim_vemdor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=50)),
            ],
        ),
    ]
