# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-05-29 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ETL', '0013_dim_vemdor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dim_vemdor',
            new_name='dim_vendor',
        ),
    ]
