# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-05-31 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETL', '0014_auto_20190530_0141'),
    ]

    operations = [
        migrations.CreateModel(
            name='dim_product_line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_line', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='dim_state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_abbr', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='dim_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_profile_date_year', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='dim_product',
            name='product_id',
        ),
        migrations.AlterField(
            model_name='dim_product',
            name='prod_abbr',
            field=models.CharField(max_length=30),
        ),
    ]
