# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-05-31 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETL', '0015_auto_20190531_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='dim_product',
            name='test',
            field=models.CharField(default=b'sfg', max_length=10),
        ),
    ]
