# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-05-31 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ETL', '0017_remove_dim_product_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='bridge_agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ETL.dim_agency')),
                ('primary_agency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ETL.dim_primary_agency')),
            ],
        ),
        migrations.CreateModel(
            name='bridge_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ETL.dim_product')),
                ('product_line_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ETL.dim_product_line')),
            ],
        ),
    ]
