# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-05-31 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ETL', '0018_bridge_agency_bridge_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bridge_agency',
            old_name='agency_id',
            new_name='agency',
        ),
        migrations.RenameField(
            model_name='bridge_agency',
            old_name='primary_agency_id',
            new_name='primary_agency',
        ),
        migrations.RenameField(
            model_name='bridge_product',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='bridge_product',
            old_name='product_line_id',
            new_name='product_line',
        ),
    ]
