# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-06-01 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ETL', '0019_auto_20190531_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='fact_insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retention_poly_qty', models.DecimalField(decimal_places=10, max_digits=30)),
                ('poly_inforce_qty', models.DecimalField(decimal_places=10, max_digits=30)),
                ('prev_poly_inforce_qty', models.DecimalField(decimal_places=10, max_digits=30)),
                ('nb_wrtn_prem_amnt', models.DecimalField(decimal_places=10, max_digits=30)),
                ('wrtn_prem_amnt', models.DecimalField(decimal_places=10, max_digits=30)),
                ('prd_ernd_prem_amt', models.DecimalField(decimal_places=10, max_digits=30)),
                ('prd_incr_losses_amt', models.DecimalField(decimal_places=10, max_digits=30)),
                ('months', models.IntegerField()),
                ('retention_ratio', models.DecimalField(decimal_places=10, max_digits=30)),
                ('loss_ratio', models.DecimalField(decimal_places=10, max_digits=30)),
                ('loss_ratio_3yr', models.DecimalField(decimal_places=10, max_digits=30)),
                ('growth_rate_3yr', models.DecimalField(decimal_places=10, max_digits=30)),
                ('cl_bound_ct_mds', models.IntegerField()),
                ('cl_quo_ct_mds', models.IntegerField()),
                ('cl_bound_ct_sbz', models.IntegerField()),
                ('cl_quo_ct_sbz', models.IntegerField()),
                ('cl_bound_ct_eqt', models.IntegerField()),
                ('cl_quo_ct_eqt', models.IntegerField()),
                ('pl_bound_ct_elinks', models.IntegerField()),
                ('pl_quo_ct_elinks', models.IntegerField()),
                ('pl_bound_ct_plrank', models.IntegerField()),
                ('pl_quo_ct_plrank', models.IntegerField()),
                ('pl_bound_ct_eqtte', models.IntegerField()),
                ('pl_quo_ct_eqtte', models.IntegerField()),
                ('pl_bound_ct_applied', models.IntegerField()),
                ('pl_quo_ct_applied', models.IntegerField()),
                ('pl_bound_ct_transactnow', models.IntegerField()),
                ('pl_quo_ct_transactnow', models.IntegerField()),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ETL.dim_agency')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ETL.dim_product')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ETL.dim_state')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ETL.dim_time')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ETL.dim_vendor')),
            ],
        ),
    ]
