# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-06-01 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETL', '0020_fact_insurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact_insurance',
            name='cl_bound_ct_eqt',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
        migrations.AlterField(
            model_name='fact_insurance',
            name='cl_bound_ct_mds',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
        migrations.AlterField(
            model_name='fact_insurance',
            name='cl_bound_ct_sbz',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
        migrations.AlterField(
            model_name='fact_insurance',
            name='cl_quo_ct_eqt',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
        migrations.AlterField(
            model_name='fact_insurance',
            name='cl_quo_ct_mds',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
        migrations.AlterField(
            model_name='fact_insurance',
            name='cl_quo_ct_sbz',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
        migrations.AlterField(
            model_name='fact_insurance',
            name='months',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
        migrations.AlterField(
            model_name='fact_insurance',
            name='pl_bound_ct_applied',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
        migrations.AlterField(
            model_name='fact_insurance',
            name='pl_bound_ct_elinks',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
        migrations.AlterField(
            model_name='fact_insurance',
            name='pl_bound_ct_eqtte',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
        migrations.AlterField(
            model_name='fact_insurance',
            name='pl_bound_ct_plrank',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
        migrations.AlterField(
            model_name='fact_insurance',
            name='pl_bound_ct_transactnow',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
        migrations.AlterField(
            model_name='fact_insurance',
            name='pl_quo_ct_applied',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
        migrations.AlterField(
            model_name='fact_insurance',
            name='pl_quo_ct_elinks',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
        migrations.AlterField(
            model_name='fact_insurance',
            name='pl_quo_ct_eqtte',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
        migrations.AlterField(
            model_name='fact_insurance',
            name='pl_quo_ct_plrank',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
        migrations.AlterField(
            model_name='fact_insurance',
            name='pl_quo_ct_transactnow',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
    ]
