# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-06-02 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ETL', '0021_auto_20190601_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dim_product',
            old_name='prod_abbr',
            new_name='PROD_ABBR',
        ),
    ]
